### ISSUE TITLE
超时控制

### ISSUE THREAD

**Issue by x-lambda** [mohuishou/protoc-gen-go-gin#2]
大佬请问一下有没有实现超时控制？以及把gin.ctx转成context.Context()对象？

**Comment by mohuishou** [comment]
1. 超时控制，这个应该是在调用的时候传入一个已经有相关中间件的 `router`
2. ctx 转换，可以看下方的实现，做了一个转换，并且用 `metadata` 库注入了 `header` 信息，在业务代码中不需要依赖 `gin.Context`
    https://github.com/mohuishou/protoc-gen-go-gin/blob/master/template.go.tpl#L103

**Comment by x-lambda** [comment]
我看了现有的转换方案
```
type mdIncomingKey struct{}

// NewIncomingContext creates a new context with incoming md attached.
func NewIncomingContext(ctx context.Context, md MD) context.Context {
	return context.WithValue(ctx, mdIncomingKey{}, md)
}
```
这里的key是私有变量，是不是意味着封装进来的md其实ctx都拿不到？

**Comment by mohuishou** [comment]
> 我看了现有的转换方案
> ```
> type mdIncomingKey struct{}
> 
> // NewIncomingContext creates a new context with incoming md attached.
> func NewIncomingContext(ctx context.Context, md MD) context.Context {
> 	return context.WithValue(ctx, mdIncomingKey{}, md)
> }
> ```
> 这里的key是私有变量，是不是意味着封装进来的md其实ctx都拿不到？

用 metadata 这个库能取到

**Comment by x-lambda** [comment]
> > 我看了现有的转换方案
> > ```
> > type mdIncomingKey struct{}
> > 
> > // NewIncomingContext creates a new context with incoming md attached.
> > func NewIncomingContext(ctx context.Context, md MD) context.Context {
> > 	return context.WithValue(ctx, mdIncomingKey{}, md)
> > }
> > ```
> > 
> > 
> > 这里的key是私有变量，是不是意味着封装进来的md其实ctx都拿不到？
> 
> 用 metadata 这个库能取到

好的，感谢大佬解答
