### ISSUE TITLE
判断错误的接口拆开会不会更好一点?

### ISSUE THREAD

**Issue by i-curve** [mohuishou/protoc-gen-go-gin#4]
![image](https://user-images.githubusercontent.com/40533808/139702132-8972ee29-42a9-4713-a4a5-a9b49affa33e.png)
如图，这里面是用了一个含有3个方法的接口。这就导致了自己写的错误不能够直接和这个兼容。

如何把这里给该成3个接口，每个接口都只有一个方法会不会更好？

**Comment by mohuishou** [comment]
也不是不可以，只是当时做的时候这三个其实都是必须的

**Comment by i-curve** [comment]
恩。自己封装了个错误的包，但是只有http状态码，message，没有code。
我还是把我那个包改造一下吧
